name: RealisticChat
main: io.github.redinzane.realisticchat.RealisticChat
version: 0.5
description: RealisticChat Plugin Beta. Has RangedChat, Cellphones, Console Logging, Cell Towers

depend:

permissions: